# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
